# Generated by Django 3.2.13 on 2023-06-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230623_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='gio_location',
            field=models.JSONField(null=True),
        ),
    ]
